### ISSUE TITLE
Wallpper list not loading

### ISSUE THREAD

**Issue by scoubymat** [adrielcafe/NoMansWallpaperApp#1]
Hello, when i open the application, wallpaper are not loading.
Don't hesitate to ask me somes questions.

**Comment by adrielcafe** [comment]
Hi @scoubymat ,

Just released a new build (1.2.3) with a *possible* fix. 

Can you check if it's working now? Thanks!

**Comment by scoubymat** [comment]
Yeah!
Thank's for your quick answer. It has fixed my problem.

Have a nice day,
Scoubymat.
